#!/bin/bash

if [ $1 != "update" ] ; then
  echo "did not call update" >&2
  exit 1
fi

if [ x$FC_TEST_TMPDIR == x ] ; then
  echo "did not set fc_test_tmpdir" >&2
  exit 2
fi

if [ ! -d $FC_TEST_TMPDIR ] ; then
  echo "FC_TEST_TMPDIR does not exists" >&2
  exit 3
fi

touch $FC_TEST_TMPDIR/dconf-updated
exit 0
