/*
 * Copyright (C) 2014 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the licence, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Matthew Barnes <mbarnes@redhat.com>
 */

#include "config.h"

#include "fcmdr-gsettings-backend.h"

#include <errno.h>
#include <string.h>

#include "fcmdr-extensions.h"
#include "fcmdr-utils.h"

#define FCMDR_GSETTINGS_BACKEND_GET_PRIVATE(obj) \
	(G_TYPE_INSTANCE_GET_PRIVATE \
	((obj), FCMDR_TYPE_GSETTINGS_BACKEND, FCmdrGSettingsBackendPrivate))

#define FCMDR_GSETTINGS_PREAMBLE \
	"# Generated by " G_LOG_DOMAIN ". DO NOT EDIT.\n\n"

struct _FCmdrGSettingsBackendPrivate {
	gint placeholder;
};

G_DEFINE_TYPE_WITH_CODE (
	FCmdrGSettingsBackend,
	fcmdr_gsettings_backend,
	FCMDR_TYPE_SERVICE_BACKEND,
	fcmdr_ensure_extension_points_registered();
	g_io_extension_point_implement (
		FCMDR_SERVICE_BACKEND_EXTENSION_POINT_NAME,
		g_define_type_id,
		"org.gnome.gsettings", 0))

static gboolean
fcmdr_gsettings_backend_write_key_file (GKeyFile *key_file,
                                        const gchar *filename,
                                        GError **error)
{
	GString *contents;
	gchar *data;
	gsize length = 0;
	gboolean success;

	contents = g_string_new (FCMDR_GSETTINGS_PREAMBLE);

	data = g_key_file_to_data (key_file, &length, NULL);
	g_string_append_len (contents, data, length);
	g_free (data);

	success = g_file_set_contents (
		filename, contents->str, contents->len, error);

	g_string_free (contents, TRUE);

	return success;
}

static gboolean
fcmdr_gsettings_backend_write_locks (GHashTable *locks,
                                     const gchar *filename,
                                     GError **error)
{
	GString *contents;
	GList *list, *link;
	gboolean success;

	contents = g_string_new (FCMDR_GSETTINGS_PREAMBLE);

	list = g_hash_table_get_keys (locks);
	list = g_list_sort (list, (GCompareFunc) strcmp);

	for (link = list; link != NULL; link = g_list_next (link)) {
		g_string_append (contents, link->data);
		g_string_append_c (contents, '\n');
	}

	g_list_free (list);

	success = g_file_set_contents (
		filename, contents->str, contents->len, error);

	g_string_free (contents, TRUE);

	return success;
}

static void
fcmdr_gsettings_backend_foreach_element_cb (JsonArray *json_array,
                                            guint index,
                                            JsonNode *json_node,
                                            gpointer user_data)
{
	GKeyFile *key_file = user_data;
	JsonObject *json_object;
	GVariant *value = NULL;
	const gchar *path;
	gchar *group;
	gchar *key;

	g_return_if_fail (JSON_NODE_HOLDS_OBJECT (json_node));

	json_object = json_node_get_object (json_node);
	g_return_if_fail (json_object_has_member (json_object, "key"));
	g_return_if_fail (json_object_has_member (json_object, "value"));

	path = json_object_get_string_member (json_object, "key");
	g_return_if_fail (path != NULL);

	/* Skip leading slashes. */
	while (*path == '/')
		path++;

	group = g_strdup (path);
	key = strrchr (group, '/');

	if (key != NULL)
		*key++ = '\0';

	json_node = json_object_get_member (json_object, "value");
	value = fcmdr_json_value_to_variant (json_node);

	/* This is how GKeyfileSettingsBackend does it. */
	if (key != NULL && value != NULL) {
		gchar *str = g_variant_print (value, FALSE);
		g_key_file_set_value (key_file, group, key, str);
		g_variant_unref (g_variant_ref_sink (value));
		g_free (str);
	}

	g_free (group);
}

static void
fcmdr_gsettings_backend_apply_profile_settings (FCmdrServiceBackend *backend,
                                                FCmdrProfile *profile)
{
	JsonNode *json_node;
	JsonArray *json_array;
	GKeyFile *key_file;
	GHashTable *locks;
	const gchar *uid;
	gchar **groups;
	gsize ii, n_groups;
	gchar *locks_path;
	gchar *locks_file;
	gchar *sysdb_name;
	gchar *sysdb_path;
	gchar *sysdb_file;

	/* The profile may not have settings for this backend. */
	json_node = fcmdr_service_backend_dup_settings (backend, profile);
	if (json_node == NULL)
		return;

	g_return_if_fail (JSON_NODE_HOLDS_ARRAY (json_node));

	key_file = g_key_file_new ();

	locks = g_hash_table_new_full (
		(GHashFunc) g_str_hash,
		(GEqualFunc) g_str_equal,
		(GDestroyNotify) g_free,
		(GDestroyNotify) NULL);

	json_array = json_node_get_array (json_node);

	json_array_foreach_element (
		json_array,
		fcmdr_gsettings_backend_foreach_element_cb,
		key_file);

	groups = g_key_file_get_groups (key_file, &n_groups);

	for (ii = 0; ii < n_groups; ii++) {
		gchar **keys;
		gsize jj, n_keys;

		keys = g_key_file_get_keys (
			key_file, groups[ii], &n_keys, NULL);

		for (jj = 0; jj < n_keys; jj++) {
			g_hash_table_add (
				locks,
				g_strdup_printf (
				"/%s/%s", groups[ii], keys[jj]));
		}

		g_strfreev (keys);
	}

	g_strfreev (groups);

	uid = fcmdr_profile_get_uid (profile);
	sysdb_name = g_strdup_printf ("fleet-commander-%s", uid);
	sysdb_path = g_strdup_printf ("/etc/dconf/db/%s.d", sysdb_name);
	sysdb_file = g_build_filename (sysdb_path, "generated", NULL);
	locks_path = g_build_filename (sysdb_path, "locks", NULL);
	locks_file = g_build_filename (locks_path, "generated", NULL);

	if (g_mkdir_with_parents (locks_path, 0755) == 0) {
		GError *local_error = NULL;

		fcmdr_gsettings_backend_write_key_file (
			key_file, sysdb_file, &local_error);

		if (local_error != NULL) {
			g_critical (
				"Failed to write file: %s: %s",
				sysdb_file, local_error->message);
			g_clear_error (&local_error);
		}

		fcmdr_gsettings_backend_write_locks (
			locks, locks_file, &local_error);

		if (local_error != NULL) {
			g_critical (
				"Failed to write file: %s: %s",
				locks_file, local_error->message);
			g_clear_error (&local_error);
		}

	} else {
		g_critical (
			"Failed to make directory: %s: %s",
			locks_path, g_strerror (errno));
	}

exit:
	json_node_free (json_node);

	g_key_file_free (key_file);
	g_hash_table_destroy (locks);

	g_free (sysdb_name);
	g_free (sysdb_path);
	g_free (sysdb_file);
	g_free (locks_path);
	g_free (locks_file);
}

static void
fcmdr_gsettings_backend_apply_profiles (FCmdrServiceBackend *backend,
                                        GList *profiles)
{
	GList *link;
	GError *local_error = NULL;

	for (link = profiles; link != NULL; link = g_list_next (link)) {
		fcmdr_gsettings_backend_apply_profile_settings (
			backend, FCMDR_PROFILE (link->data));
	}

	g_spawn_command_line_sync (
		DCONF_PATH " update", NULL, NULL, NULL, &local_error);

	if (local_error != NULL) {
		g_critical (
			"Failed to spawn dconf tool: %s",
			local_error->message);
		g_clear_error (&local_error);
	}
}

static void
fcmdr_gsettings_backend_class_init (FCmdrGSettingsBackendClass *class)
{
	FCmdrServiceBackendClass *backend_class;

	g_type_class_add_private (
		class, sizeof (FCmdrGSettingsBackendPrivate));

	backend_class = FCMDR_SERVICE_BACKEND_CLASS (class);
	backend_class->apply_profiles = fcmdr_gsettings_backend_apply_profiles;
}

static void
fcmdr_gsettings_backend_init (FCmdrGSettingsBackend *backend)
{
	backend->priv = FCMDR_GSETTINGS_BACKEND_GET_PRIVATE (backend);
}

